defmodule OrchestraFunctions do
  defguard is_atomic_type(t) when t in [:tatomic_int, :tatomic_float, :tatomic_double]

  # The functions_lookup map is used to store the name, return type, argument types and the generated OpenCL name
  # of Orchestra DSL built-in functions. If the function does not have a different name in OpenCL, you can leave
  # the opencl_name field as nil, and it will be generated by the backend using the function name.
  @functions_lookup %{
    get_global_id: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_global_size: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_local_id: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_local_size: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_group_id: %{
      return_type: :int,
      arg_types: [:int]
    },
    get_num_groups: %{
      return_type: :int,
      arg_types: [:int]
    },
    sqrt: %{
      return_type: :float,
      arg_types: [:float]
    },
    sqrtf: %{
      return_type: :float,
      arg_types: [:float],
      opencl_name: "sqrt"
    },
    max: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    fmaxf: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    min: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    fminf: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    cas_int: %{
      return_type: :int,
      arg_types: [:int, :int, :int]
    },
    cas_float: %{
      return_type: :float,
      arg_types: [:float, :float, :float]
    },
    cas_double: %{
      return_type: :double,
      arg_types: [:double, :double, :double]
    },
    sin: %{
      return_type: :float,
      arg_types: [:float]
    },
    cos: %{
      return_type: :float,
      arg_types: [:float]
    },
    tan: %{
      return_type: :float,
      arg_types: [:float]
    },
    exp: %{
      return_type: :float,
      arg_types: [:float]
    },
    log: %{
      return_type: :float,
      arg_types: [:float]
    },
    pow: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    trunc: %{
      return_type: :int,
      arg_types: [:float]
    },
    abs: %{
      return_type: :int,
      arg_types: [:int]
    },
    fabs: %{
      return_type: :float,
      arg_types: [:float]
    },
    fmod: %{
      return_type: :float,
      arg_types: [:float, :float]
    },
    clamp: %{
      return_type: :float,
      arg_types: [:float, :float, :float]
    },
    __syncthreads: %{
      return_type: :unit,
      arg_types: []
    },
    # --- Atomics ---
    atomic_add_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    atomic_add_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    atomic_add_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    atomic_sub_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    atomic_sub_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    atomic_sub_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    atomic_exchange_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    atomic_exchange_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    atomic_exchange_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    atomic_min_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    atomic_min_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    atomic_min_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    atomic_max_int: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    atomic_max_float: %{
      return_type: :float,
      arg_types: [:tatomic_float, :float],
    },
    atomic_max_double: %{
      return_type: :double,
      arg_types: [:tatomic_double, :double],
    },
    atomic_and: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    atomic_or: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    },
    atomic_xor: %{
      return_type: :int,
      arg_types: [:tatomic_int, :int],
    }
  }

  # Create a lookup function clause for each function in the functions_lookup map
  for {fun_name, info} <- @functions_lookup do
    def lookup(unquote(fun_name)) do
      unquote(Macro.escape(info))
    end

    def exists?(unquote(fun_name)) do
      true
    end
  end

  # Clauses when the function is not found in the lookup
  def lookup(_fun) do
    nil
  end

  def exists?(_fun) do
    false
  end
end
